//
// DrugCoverageAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension vericred_clientAPI {


public class DrugCoverageAPI: APIBase {
    /**
     Find Drug Coverages for a given NDC
     
     - parameter ndc: (path) NDC for a drug 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func drugsNdcCoveragesGet(ndc ndc: String, completion: ((data: [DrugCoverage]?, error: ErrorType?) -> Void)) {
        drugsNdcCoveragesGetWithRequestBuilder(ndc: ndc).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Find Drug Coverages for a given NDC
     - GET /drugs/{ndc}/coverages
     - Drug Coverages are the specific tier level, quantity limit, prior authorization
and step therapy for a given Drug/Plan combination.  This endpoint returns
all DrugCoverages for a given Drug


     - examples: [{contentType=application/json, example={
  "coverages" : [ {
    "plan_id" : "98825NY2251359",
    "tier" : "TIER 1",
    "quantity_limit" : true,
    "prior_authorization" : true,
    "step_therapy" : false
  }, {
    "plan_id" : "98825NY2251358",
    "tier" : "TIER 1",
    "quantity_limit" : false,
    "prior_authorization" : true,
    "step_therapy" : true
  }, {
    "plan_id" : "98825NY2251357",
    "tier" : "TIER 1",
    "quantity_limit" : true,
    "prior_authorization" : true,
    "step_therapy" : true
  }, {
    "plan_id" : "98825NY2251356",
    "tier" : "TIER 1",
    "quantity_limit" : true,
    "prior_authorization" : false,
    "step_therapy" : false
  }, {
    "plan_id" : "98825NY2251355",
    "tier" : "TIER 1",
    "quantity_limit" : false,
    "prior_authorization" : true,
    "step_therapy" : true
  } ]
}}]
     
     - parameter ndc: (path) NDC for a drug 

     - returns: RequestBuilder<[DrugCoverage]> 
     */
    public class func drugsNdcCoveragesGetWithRequestBuilder(ndc ndc: String) -> RequestBuilder<[DrugCoverage]> {
        var path = "/drugs/{ndc}/coverages"
        path = path.stringByReplacingOccurrencesOfString("{ndc}", withString: "\(ndc)", options: .LiteralSearch, range: nil)
        let URLString = vericred_clientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[DrugCoverage]>.Type = vericred_clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
}
