//
// DrugCoveragesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension vericred_clientAPI {


public class DrugCoveragesAPI: APIBase {
    /**
     Search for DrugCoverages
     
     - parameter ndcPackageCode: (path) NDC package code 
     - parameter audience: (query) Plan Audience (individual or small_group) 
     - parameter stateCode: (query) Two-character state code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDrugCoverages(ndcPackageCode ndcPackageCode: String, audience: String, stateCode: String, completion: ((data: DrugCoverageResponse?, error: ErrorType?) -> Void)) {
        getDrugCoveragesWithRequestBuilder(ndcPackageCode: ndcPackageCode, audience: audience, stateCode: stateCode).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search for DrugCoverages
     - GET /drug_packages/{ndcPackageCode}/coverages
     - Drug Coverages are the specific tier level, quantity limit, prior authorization and step therapy for a given Drug/Plan combination. This endpoint returns all DrugCoverages for a given Drug.  #### Tiers   Possible values for tier:    | Tier                     | Description                                                                                                                                                                     |   | ------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |   | __generic__              | Unbranded drugs, with the same active ingredients as their brand-name equivalents, and generally available at a lower cost.                                                     |   | __preferred_brand__      | Brand-name drugs included on the health plan's formulary. Generally more expensive than generics, and less expensive than non-preferred drugs.                                  |   | __non_preferred_brand__  | Brand-name drugs not included on the health plan's formulary. These generally have a higher coinsurance.                                                                        |   | __specialty__            | Used to treat complex conditions like cancer. May require special handling or monitoring. May be generic or brand-name. Generally the most expensive drugs covered by a plan.   |   | __not_covered__          | Specifically excluded from the health plan.                                                                                                                                     |   | __not_listed__           | Neither included nor excluded from the health plan. Most plans provide some default level of coverage for unlisted drugs.                                                       |
     - API Key:
       - type: apiKey Vericred-Api-Key 
       - name: Vericred-Api-Key
     - examples: [{contentType=application/json, example="{\n  \"coverages\" : [ {\n    \"plan_id\" : \"98825NY2251359\",\n    \"ndc_package_code\" : \"00000-0000-00\",\n    \"tier\" : \"TIER 1\",\n    \"quantity_limit\" : true,\n    \"prior_authorization\" : true,\n    \"step_therapy\" : false\n  } ]\n}"}]
     
     - parameter ndcPackageCode: (path) NDC package code 
     - parameter audience: (query) Plan Audience (individual or small_group) 
     - parameter stateCode: (query) Two-character state code 

     - returns: RequestBuilder<DrugCoverageResponse> 
     */
    public class func getDrugCoveragesWithRequestBuilder(ndcPackageCode ndcPackageCode: String, audience: String, stateCode: String) -> RequestBuilder<DrugCoverageResponse> {
        var path = "/drug_packages/{ndcPackageCode}/coverages"
        path = path.stringByReplacingOccurrencesOfString("{ndcPackageCode}", withString: "\(ndcPackageCode)", options: .LiteralSearch, range: nil)
        let URLString = vericred_clientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "audience": audience,
            "state_code": stateCode
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<DrugCoverageResponse>.Type = vericred_clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
}
