//
// NetworksAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension vericred_clientAPI {


public class NetworksAPI: APIBase {
    /**
     Networks
     
     - parameter carrierId: (query) Carrier HIOS Issuer ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listNetworks(carrierId carrierId: String, completion: ((data: NetworkSearchResponse?, error: ErrorType?) -> Void)) {
        listNetworksWithRequestBuilder(carrierId: carrierId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Networks
     - GET /networks
     - A network is a list of the doctors, other health care providers,
and hospitals that a plan has contracted with to provide medical care to
its members.
     - examples: [{contentType=application/json, example={
  "meta" : {
    "total" : ""
  },
  "networks" : [ {
    "name" : "aeiou",
    "id" : ""
  } ]
}}]
     
     - parameter carrierId: (query) Carrier HIOS Issuer ID 

     - returns: RequestBuilder<NetworkSearchResponse> 
     */
    public class func listNetworksWithRequestBuilder(carrierId carrierId: String) -> RequestBuilder<NetworkSearchResponse> {
        let path = "/networks"
        let URLString = vericred_clientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "carrier_id": carrierId
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<NetworkSearchResponse>.Type = vericred_clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

}
}
