//
// PlansAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension vericred_clientAPI {


public class PlansAPI: APIBase {
    /**
     Find a set of plans for a Zip Code and County
     
     - parameter query: (body) Plan query 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func plansFindPost(query query: Query, completion: ((data: [Plan]?, error: ErrorType?) -> Void)) {
        plansFindPostWithRequestBuilder(query: query).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Find a set of plans for a Zip Code and County
     - POST /plans/find
     - ### Location Information

Searching for a set of plans requires a `zip_code` and `fips_code`
code.  These are used to determine pricing and availabity
of health plans.

Optionally, you may provide a list of Applicants or Providers

### Applicants

This is a list of people who will be covered by the plan.  We
use this list to calculate the premium.  You must include `age`
and can include `smoker`, which also factors into pricing in some
states.

Applicants *must* include an age.  If smoker is omitted, its value is assumed
to be false.

#### Multiple Applicants

To get pricing for multiple applicants, just append multiple sets
of data to the URL with the age and smoking status of each applicant
next to each other.

For example, given two applicants - one age 32 and a non-smoker and one
age 29 and a smoker, you could use the following request

`GET /plans?zip_code=07451&fips_code=33025&applicants[][age]=32&applicants[][age]=29&applicants[][smoker]=true`

It would also be acceptible to include `applicants[][smoker]=false` after the
first applicant's age.

### Providers

We identify Providers (Doctors) by their National Practitioner
Index number (NPI).  If you pass a list of Providers, keyed by
their NPI number, we will return a list of which Providers are
in and out of network for each plan returned.

For example, if we had two providers with the NPI numbers `12345` and `23456`
you would make the following request

`GET /plans?zip_code=07451&fips_code=33025&providers[][npi]=12345&providers[][npi]=23456`

### Enrollment Date

To calculate plan pricing and availability, we default to the current date
as the enrollment date.  To specify a date in the future (or the past), pass
a string with the format `YYYY-MM-DD` in the `enrollment_date` parameter.

`GET /plans?zip_code=07451&fips_code=33025&enrollment_date=2016-01-01`

### Subsidy

On-marketplace plans are eligible for a subsidy based on the
`household_size` and `household_income` of the applicants.  If you
pass those values, we will calculate the `subsidized_premium`
and return it for each plan.  If no values are provided, the
`subsidized_premium` will be the same as the `premium`

`GET /plans?zip_code=07451&fips_code=33025&household_size=4&household_income=40000`


     - examples: [{contentType=application/json, example={
  "plans" : [ {
    "adult_dental" : true,
    "benefits_summary_url" : "http://www.emblemhealth.com/~/media/Files/PDF/HIXHub/BenefitSummary_SelectCareSilver.pdf",
    "buy_link" : "http://www.healthbenefitexchange.ny.gov/",
    "carrier_name" : "EmblemHealth",
    "child_dental" : "",
    "customer_service_phone_number" : "1-866-640-3889",
    "drug_formulary_url" : "http://www.emblemhealth.com/~/media/Files/PDF/Pharmacy/ValuePlus_Formulary.pdf",
    "emergency_room" : "Deductible, then $150",
    "family_drug_deductible" : "Included in Medical",
    "family_drug_moop" : "Included in Medical",
    "family_medical_deductible" : "$4,000",
    "family_medical_moop" : "$11,000",
    "generic_drugs" : "$10",
    "id" : "88582NY0230001",
    "in_network_ids" : [ 123456789, 234567890 ],
    "individual_drug_deductible" : "Included in Medical",
    "individual_drug_moop" : "Included in Medical",
    "individual_medical_deductible" : "$2,000",
    "individual_medical_moop" : "$5,500",
    "inpatient_facility" : "Deductible, then $1,500 per admission\"",
    "inpatient_physician" : "Included in inpatient facility",
    "level" : "silver",
    "logo_url" : "https://d1hm12jr612u3r.cloudfront.net/images/carriers/174/1438891372/thumb.png?1438891372",
    "name" : "Select Care Silver, Age 29 Rider",
    "non_preferred_brand_drugs" : "$70",
    "out_of_network_coverage" : "",
    "out_of_network_ids" : [ 123456789, 234567890 ],
    "plan_market" : "shop",
    "plan_type" : "HMO",
    "preferred_brand_drugs" : "$35",
    "premium_subsidized" : 321.5,
    "premium" : 533.24,
    "primary_care_physician" : "Deductible, then $30",
    "specialist" : "Deductible, then $50",
    "specialty_drugs" : "$70"
  } ]
}}]
     
     - parameter query: (body) Plan query 

     - returns: RequestBuilder<[Plan]> 
     */
    public class func plansFindPostWithRequestBuilder(query query: Query) -> RequestBuilder<[Plan]> {
        let path = "/plans/find"
        let URLString = vericred_clientAPI.basePath + path
        let parameters = query.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<[Plan]>.Type = vericred_clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

}
}
