//
// CarrierSubsidiary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CarrierSubsidiary: JSONEncodable {
    /** Primary key */
    public var id: Int32?
    /** Subsidiary name */
    public var name: String?
    /** Parent Carrier Name */
    public var alternateName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["alternate_name"] = self.alternateName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
