//
// CountyBulk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CountyBulk: JSONEncodable {
    /** FIPs code for the county */
    public var id: String?
    /** Name of the county */
    public var name: String?
    /** State code */
    public var stateId: String?
    /** Count of unique rating areas in the county */
    public var ratingAreaCount: String?
    /** Count of unique service areas in the county */
    public var serviceAreaCount: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["state_id"] = self.stateId
        nillableDictionary["rating_area_count"] = self.ratingAreaCount
        nillableDictionary["service_area_count"] = self.serviceAreaCount
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
