//
// County.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class County: JSONEncodable {
    /** Primary key */
    public var id: Int32?
    /** State FIPS code */
    public var fipsCode: String?
    /** Human-readable name */
    public var name: String?
    /** Two-character state code */
    public var stateCode: String?
    /** state relationship */
    public var stateId: Int32?
    /** Is the state containing this county active for consumers?(deprecated in favor of last_date_for_individual) */
    public var stateLive: Bool?
    /** Is the state containing this county active for business?(deprecated in favor of last_date_for_shop) */
    public var stateLiveForBusiness: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["fips_code"] = self.fipsCode
        nillableDictionary["name"] = self.name
        nillableDictionary["state_code"] = self.stateCode
        nillableDictionary["state_id"] = self.stateId?.encodeToJSON()
        nillableDictionary["state_live"] = self.stateLive
        nillableDictionary["state_live_for_business"] = self.stateLiveForBusiness
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
