//
// DrugCoverageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DrugCoverageResponse: JSONEncodable {
    /** Meta-data */
    public var meta: Meta?
    /** DrugCoverage search results */
    public var drugCoverages: [DrugCoverage]?
    /** Drug */
    public var drugs: [Drug]?
    /** Drug Packages */
    public var drugPackages: [DrugPackage]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        nillableDictionary["drug_coverages"] = self.drugCoverages?.encodeToJSON()
        nillableDictionary["drugs"] = self.drugs?.encodeToJSON()
        nillableDictionary["drug_packages"] = self.drugPackages?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
