//
// Drug.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Drug: JSONEncodable {
    /** National Drug Code ID */
    public var ndc: String?
    /** Proprietary name of drug */
    public var proprietaryName: String?
    /** Non-proprietary name of drug */
    public var nonProprietaryName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ndc"] = self.ndc
        nillableDictionary["proprietary_name"] = self.proprietaryName
        nillableDictionary["non_proprietary_name"] = self.nonProprietaryName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
