//
// DrugCoverage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DrugCoverage: JSONEncodable {
    /** Health Insurance Oversight System id */
    public var planId: String?
    /** NDC package code */
    public var drugPackageId: String?
    /** Tier Name */
    public var tier: String?
    /** Quantity limit exists */
    public var quantityLimit: Bool?
    /** Prior authorization required */
    public var priorAuthorization: Bool?
    /** Step Treatment required */
    public var stepTherapy: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["plan_id"] = self.planId
        nillableDictionary["drug_package_id"] = self.drugPackageId
        nillableDictionary["tier"] = self.tier
        nillableDictionary["quantity_limit"] = self.quantityLimit
        nillableDictionary["prior_authorization"] = self.priorAuthorization
        nillableDictionary["step_therapy"] = self.stepTherapy
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
