//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2002: JSONEncodable {
    public var zipCounties: [ZipCounty]?
    public var counties: [County]?
    public var zipCodes: [ZipCode]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["zip_counties"] = self.zipCounties?.encodeToJSON()
        nillableDictionary["counties"] = self.counties?.encodeToJSON()
        nillableDictionary["zip_codes"] = self.zipCodes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
