//
// NetworkDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NetworkDetails: JSONEncodable {
    /** Primary key */
    public var id: Int32?
    /** Name of the Network */
    public var name: String?
    /** List of issuer IDs */
    public var hiosIssuerIds: [Int32]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["hios_issuer_ids"] = self.hiosIssuerIds?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
