//
// NetworkSize.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NetworkSize: JSONEncodable {
    /** Foreign key to Network */
    public var networkId: Int32?
    /** Number of Providers in-network in this State */
    public var count: Int32?
    /** Foreign key to State */
    public var stateId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["network_id"] = self.networkId?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["state_id"] = self.stateId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
