//
// PlanSearchResponseMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PlanSearchResponseMeta: JSONEncodable {
    /** Number of entities returned */
    public var total: Int32?
    /** Is this applicant potentially eligible for Chip or Medicaid? */
    public var eligibleForChipMedicaid: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["eligible_for_chip_medicaid"] = self.eligibleForChipMedicaid
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
