//
// Plan.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Plan: JSONEncodable {
    /** Does the plan provide dental coverage for adults? */
    public var adultDental: Bool?
    /** Benefits string for ambulance coverage */
    public var ambulance: String?
    /** Link to the summary of benefits and coverage (SBC) document. */
    public var benefitsSummaryUrl: String?
    /** Link to a location to purchase the plan. */
    public var buyLink: String?
    /** Name of the insurance carrier */
    public var carrierName: String?
    /** Does the plan provide dental coverage for children? */
    public var childDental: Bool?
    /** Child eyewear benefits summary */
    public var childEyewear: String?
    /** Phone number to contact the insurance carrier */
    public var customerServicePhoneNumber: String?
    /** Benefits summary for durable medical equipment */
    public var durableMedicalEquipment: String?
    /** Diagnostic tests benefit summary */
    public var diagnosticTest: String?
    /** Link to the summary of drug benefits for the plan */
    public var drugFormularyUrl: String?
    /** Description of costs when visiting the ER */
    public var emergencyRoom: String?
    /** Deductible for drugs when a family is on the plan. */
    public var familyDrugDeductible: String?
    /** Maximum out-of-pocket for drugs when a family is on the plan */
    public var familyDrugMoop: String?
    /** Deductible when a family is on the plan */
    public var familyMedicalDeductible: String?
    /** Maximum out-of-pocket when a family is on the plan */
    public var familyMedicalMoop: String?
    /** Cost for generic drugs */
    public var genericDrugs: String?
    /**  */
    public var hiosIssuerId: String?
    /** Government-issued HIOS plan ID */
    public var id: String?
    /** Benefits summary for imaging coverage */
    public var imaging: String?
    /** Deductible for drugs when an individual is on the plan */
    public var individualDrugDeductible: String?
    /** Maximum out-of-pocket for drugs when an individual is on the plan */
    public var individualDrugMoop: String?
    /** Deductible when an individual is on the plan */
    public var individualMedicalDeductible: String?
    /** Maximum out-of-pocket when an individual is on the plan */
    public var individualMedicalMoop: String?
    /** Cost under the plan for an inpatient facility */
    public var inpatientFacility: String?
    /** Cost under the plan for an inpatient physician */
    public var inpatientPhysician: String?
    /** Plan metal grouping (e.g. platinum, gold, silver, etc) */
    public var level: String?
    /** Link to a copy of the insurance carrier&#39;s logo */
    public var logoUrl: String?
    /** Marketing name of the plan */
    public var name: String?
    /** Total number of Providers in network */
    public var networkSize: Int32?
    /** Cost under the plan for non-preferred brand drugs */
    public var nonPreferredBrandDrugs: String?
    /** Is the plan on-market? */
    public var onMarket: Bool?
    /** Is the plan off-market? */
    public var offMarket: Bool?
    /** Does this plan provide any out of network coverage? */
    public var outOfNetworkCoverage: Bool?
    /** Benefits summary for outpatient facility coverage */
    public var outpatientFacility: String?
    /** Benefits summary for outpatient mental health coverage */
    public var outpatientMentalHealth: String?
    /** Benefits summary for outpatient physician coverage */
    public var outpatientPhysician: String?
    /** Market in which the plan is offered (on_marketplace, shop, etc) */
    public var planMarket: String?
    /** Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity) */
    public var planType: String?
    /** Cost under the plan for perferred brand drugs */
    public var preferredBrandDrugs: String?
    /** Benefits summary for preventative care */
    public var preventativeCare: String?
    /** Cost under the plan to visit a Primary Care Physician */
    public var primaryCarePhysician: String?
    /** Benefits summary for rehabilitation services */
    public var rehabilitationServices: String?
    /** Cost under the plan to visit a specialist */
    public var specialist: String?
    /** Cost under the plan for specialty drugs */
    public var specialtyDrugs: String?
    /** Benefits summary for urgent care */
    public var urgentCare: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["adult_dental"] = self.adultDental
        nillableDictionary["ambulance"] = self.ambulance
        nillableDictionary["benefits_summary_url"] = self.benefitsSummaryUrl
        nillableDictionary["buy_link"] = self.buyLink
        nillableDictionary["carrier_name"] = self.carrierName
        nillableDictionary["child_dental"] = self.childDental
        nillableDictionary["child_eyewear"] = self.childEyewear
        nillableDictionary["customer_service_phone_number"] = self.customerServicePhoneNumber
        nillableDictionary["durable_medical_equipment"] = self.durableMedicalEquipment
        nillableDictionary["diagnostic_test"] = self.diagnosticTest
        nillableDictionary["drug_formulary_url"] = self.drugFormularyUrl
        nillableDictionary["emergency_room"] = self.emergencyRoom
        nillableDictionary["family_drug_deductible"] = self.familyDrugDeductible
        nillableDictionary["family_drug_moop"] = self.familyDrugMoop
        nillableDictionary["family_medical_deductible"] = self.familyMedicalDeductible
        nillableDictionary["family_medical_moop"] = self.familyMedicalMoop
        nillableDictionary["generic_drugs"] = self.genericDrugs
        nillableDictionary["hios_issuer_id"] = self.hiosIssuerId
        nillableDictionary["id"] = self.id
        nillableDictionary["imaging"] = self.imaging
        nillableDictionary["individual_drug_deductible"] = self.individualDrugDeductible
        nillableDictionary["individual_drug_moop"] = self.individualDrugMoop
        nillableDictionary["individual_medical_deductible"] = self.individualMedicalDeductible
        nillableDictionary["individual_medical_moop"] = self.individualMedicalMoop
        nillableDictionary["inpatient_facility"] = self.inpatientFacility
        nillableDictionary["inpatient_physician"] = self.inpatientPhysician
        nillableDictionary["level"] = self.level
        nillableDictionary["logo_url"] = self.logoUrl
        nillableDictionary["name"] = self.name
        nillableDictionary["network_size"] = self.networkSize?.encodeToJSON()
        nillableDictionary["non_preferred_brand_drugs"] = self.nonPreferredBrandDrugs
        nillableDictionary["on_market"] = self.onMarket
        nillableDictionary["off_market"] = self.offMarket
        nillableDictionary["out_of_network_coverage"] = self.outOfNetworkCoverage
        nillableDictionary["outpatient_facility"] = self.outpatientFacility
        nillableDictionary["outpatient_mental_health"] = self.outpatientMentalHealth
        nillableDictionary["outpatient_physician"] = self.outpatientPhysician
        nillableDictionary["plan_market"] = self.planMarket
        nillableDictionary["plan_type"] = self.planType
        nillableDictionary["preferred_brand_drugs"] = self.preferredBrandDrugs
        nillableDictionary["preventative_care"] = self.preventativeCare
        nillableDictionary["primary_care_physician"] = self.primaryCarePhysician
        nillableDictionary["rehabilitation_services"] = self.rehabilitationServices
        nillableDictionary["specialist"] = self.specialist
        nillableDictionary["specialty_drugs"] = self.specialtyDrugs
        nillableDictionary["urgent_care"] = self.urgentCare
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
