//
// PlanSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PlanSearchResponse: JSONEncodable {
    /** Meta-data */
    public var meta: Meta?
    /** Plan search results */
    public var plans: [Plan]?
    /** Coverages associated with the plan. */
    public var coverages: [DrugCoverage]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        nillableDictionary["plans"] = self.plans?.encodeToJSON()
        nillableDictionary["coverages"] = self.coverages?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
