//
// Pricing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Pricing: JSONEncodable {
    /** Age of applicant */
    public var age: Int32?
    /** Effective date of plan */
    public var effectiveDate: NSDate?
    /** Plan expiration date */
    public var expirationDate: NSDate?
    /** Foreign key to plans */
    public var planId: Int32?
    /** Child-only premium */
    public var premiumChildOnly: Double?
    /** Family premium */
    public var premiumFamily: Double?
    /** Single-person premium */
    public var premiumSingle: Double?
    /** Single person including children premium */
    public var premiumSingleAndChildren: Double?
    /** Person with spouse premium */
    public var premiumSingleAndSpouse: Double?
    /** Premium for single smoker */
    public var premiumSingleSmoker: Double?
    /** Foreign key to rating areas */
    public var ratingAreaId: String?
    /** Where was this pricing data extracted from? */
    public var premiumSource: String?
    /** Time when pricing was last updated */
    public var updatedAt: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["age"] = self.age?.encodeToJSON()
        nillableDictionary["effective_date"] = self.effectiveDate?.encodeToJSON()
        nillableDictionary["expiration_date"] = self.expirationDate?.encodeToJSON()
        nillableDictionary["plan_id"] = self.planId?.encodeToJSON()
        nillableDictionary["premium_child_only"] = self.premiumChildOnly
        nillableDictionary["premium_family"] = self.premiumFamily
        nillableDictionary["premium_single"] = self.premiumSingle
        nillableDictionary["premium_single_and_children"] = self.premiumSingleAndChildren
        nillableDictionary["premium_single_and_spouse"] = self.premiumSingleAndSpouse
        nillableDictionary["premium_single_smoker"] = self.premiumSingleSmoker
        nillableDictionary["rating_area_id"] = self.ratingAreaId
        nillableDictionary["premium_source"] = self.premiumSource
        nillableDictionary["updated_at"] = self.updatedAt
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
