//
// Provider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Provider: JSONEncodable {
    /** Is this provider accepting patients with a change of insurance? */
    public var acceptingChangeOfPayorPatients: Bool?
    /** Is this provider accepting new Medicaid patients? */
    public var acceptingMedicaidPatients: Bool?
    /** Is this provider accepting new Medicare patients? */
    public var acceptingMedicarePatients: Bool?
    /** Is this provider accepting new patients with private insurance? */
    public var acceptingPrivatePatients: Bool?
    /** Is this provider accepting new patients via referrals? */
    public var acceptingReferralPatients: Bool?
    /** City name (e.g. Springfield). */
    public var city: String?
    /** Primary email address to contact the provider. */
    public var email: String?
    /** Provider&#39;s gender (M or F) */
    public var gender: String?
    /** Given name for the provider. */
    public var firstName: String?
    /** List of HIOS ids for this provider */
    public var hiosIds: [String]?
    /** National Provider Index (NPI) number */
    public var id: Int32?
    /** Family name for the provider. */
    public var lastName: String?
    /** Latitude of provider */
    public var latitude: Double?
    /** Longitude of provider */
    public var longitude: Double?
    /** Middle name for the provider. */
    public var middleName: String?
    /** Personal contact phone for the provider. */
    public var personalPhone: String?
    /** Office phone for the provider */
    public var phone: String?
    /** Preferred name for display (e.g. Dr. Francis White may prefer Dr. Frank White) */
    public var presentationName: String?
    /** Name of the primary Specialty */
    public var specialty: String?
    /** State code for the provider&#39;s address (e.g. NY). */
    public var state: String?
    /** Foreign key to States */
    public var stateId: Int32?
    /** First line of the provider&#39;s street address. */
    public var streetLine1: String?
    /** Second line of the provider&#39;s street address. */
    public var streetLine2: String?
    /** Suffix for the provider&#39;s name (e.g. Jr) */
    public var suffix: String?
    /** Professional title for the provider (e.g. Dr). */
    public var title: String?
    /** Type of NPI number (individual provider vs organization). */
    public var type: String?
    /** Postal code for the provider&#39;s address (e.g. 11215) */
    public var zipCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["accepting_change_of_payor_patients"] = self.acceptingChangeOfPayorPatients
        nillableDictionary["accepting_medicaid_patients"] = self.acceptingMedicaidPatients
        nillableDictionary["accepting_medicare_patients"] = self.acceptingMedicarePatients
        nillableDictionary["accepting_private_patients"] = self.acceptingPrivatePatients
        nillableDictionary["accepting_referral_patients"] = self.acceptingReferralPatients
        nillableDictionary["city"] = self.city
        nillableDictionary["email"] = self.email
        nillableDictionary["gender"] = self.gender
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["hios_ids"] = self.hiosIds?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["middle_name"] = self.middleName
        nillableDictionary["personal_phone"] = self.personalPhone
        nillableDictionary["phone"] = self.phone
        nillableDictionary["presentation_name"] = self.presentationName
        nillableDictionary["specialty"] = self.specialty
        nillableDictionary["state"] = self.state
        nillableDictionary["state_id"] = self.stateId?.encodeToJSON()
        nillableDictionary["street_line_1"] = self.streetLine1
        nillableDictionary["street_line_2"] = self.streetLine2
        nillableDictionary["suffix"] = self.suffix
        nillableDictionary["title"] = self.title
        nillableDictionary["type"] = self.type
        nillableDictionary["zip_code"] = self.zipCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
