//
// Query.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Query: JSONEncodable {
    public var applicants: [Applicant]?
    public var enrollmentDate: NSDate?
    public var fipsCode: String?
    public var householdIncome: String?
    public var householdSize: String?
    public var market: String?
    public var providers: [String]?
    public var zipCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["applicants"] = self.applicants?.encodeToJSON()
        nillableDictionary["enrollment_date"] = self.enrollmentDate?.encodeToJSON()
        nillableDictionary["fips_code"] = self.fipsCode
        nillableDictionary["household_income"] = self.householdIncome
        nillableDictionary["household_size"] = self.householdSize
        nillableDictionary["market"] = self.market
        nillableDictionary["providers"] = self.providers?.encodeToJSON()
        nillableDictionary["zip_code"] = self.zipCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
