//
// RequestPlanFindApplicant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RequestPlanFindApplicant: JSONEncodable {
    /** Age of applicant to search for */
    public var age: Int32?
    /** Is this applicant a child? */
    public var child: Bool?
    /** Does this applicant smoke? */
    public var smoker: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["age"] = self.age?.encodeToJSON()
        nillableDictionary["child"] = self.child
        nillableDictionary["smoker"] = self.smoker
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
