//
// RequestPlanFind.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RequestPlanFind: JSONEncodable {
    /** Applicants for desired plans. */
    public var applicants: [RequestPlanFindApplicant]?
    /** Date of enrollment */
    public var enrollmentDate: String?
    /** National Drug Code Package Id */
    public var drugPackages: [DrugPackage]?
    /** County code to determine eligibility */
    public var fipsCode: String?
    /** Total household income. */
    public var householdIncome: Int32?
    /** Number of people living in household. */
    public var householdSize: Int32?
    /** Type of plan to search for. */
    public var market: String?
    /** List of providers to search for. */
    public var providers: [RequestPlanFindProvider]?
    /** 5-digit zip code - this helps determine pricing. */
    public var zipCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["applicants"] = self.applicants?.encodeToJSON()
        nillableDictionary["enrollment_date"] = self.enrollmentDate
        nillableDictionary["drug_packages"] = self.drugPackages?.encodeToJSON()
        nillableDictionary["fips_code"] = self.fipsCode
        nillableDictionary["household_income"] = self.householdIncome?.encodeToJSON()
        nillableDictionary["household_size"] = self.householdSize?.encodeToJSON()
        nillableDictionary["market"] = self.market
        nillableDictionary["providers"] = self.providers?.encodeToJSON()
        nillableDictionary["zip_code"] = self.zipCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
