//
// RequestProvidersSearch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RequestProvidersSearch: JSONEncodable {
    /** Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true */
    public var acceptsInsurance: Bool?
    /** List of HIOS ids */
    public var hiosIds: [String]?
    /** Minimum search threshold to be included in the results */
    public var minScore: Double?
    /** Page number */
    public var page: Int32?
    /** Number of records to return per page */
    public var perPage: Int32?
    /** Radius (in miles) to use to limit results */
    public var radius: Int32?
    /** String to search by */
    public var searchTerm: String?
    /** Zip Code to search near */
    public var zipCode: String?
    /** Either organization or individual */
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["accepts_insurance"] = self.acceptsInsurance
        nillableDictionary["hios_ids"] = self.hiosIds?.encodeToJSON()
        nillableDictionary["min_score"] = self.minScore
        nillableDictionary["page"] = self.page?.encodeToJSON()
        nillableDictionary["per_page"] = self.perPage?.encodeToJSON()
        nillableDictionary["radius"] = self.radius?.encodeToJSON()
        nillableDictionary["search_term"] = self.searchTerm
        nillableDictionary["zip_code"] = self.zipCode
        nillableDictionary["type"] = self.type
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
