//
// ServiceAreaZipCounty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ServiceAreaZipCounty: JSONEncodable {
    /** Foreign key to county */
    public var countyId: String?
    /** Foreign key to service area */
    public var serviceAreaId: String?
    /** Foreign key to zip code */
    public var zipCodeId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["county_id"] = self.countyId
        nillableDictionary["service_area_id"] = self.serviceAreaId
        nillableDictionary["zip_code_id"] = self.zipCodeId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
