//
// State.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class State: JSONEncodable {
    /** Primary Key of State */
    public var id: Int32?
    /** Name of state */
    public var name: String?
    /** 2 letter code for state */
    public var code: String?
    /** National FIPs number */
    public var fipsNumber: String?
    /** Last date this state is live for individuals */
    public var lastDateForIndividual: NSDate?
    /** Last date this state is live for shop */
    public var lastDateForShop: NSDate?
    /** Is this State available for businesses */
    public var liveForBusiness: Bool?
    /** Is this State available for individuals */
    public var liveForConsumers: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["code"] = self.code
        nillableDictionary["fips_number"] = self.fipsNumber
        nillableDictionary["last_date_for_individual"] = self.lastDateForIndividual?.encodeToJSON()
        nillableDictionary["last_date_for_shop"] = self.lastDateForShop?.encodeToJSON()
        nillableDictionary["live_for_business"] = self.liveForBusiness
        nillableDictionary["live_for_consumers"] = self.liveForConsumers
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
