//
// StateNetworkSizeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class StateNetworkSizeRequest: JSONEncodable {
    /** List of Network Ids */
    public var networkIds: [Int32]?
    /** List of State Ids */
    public var stateIds: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["network_ids"] = self.networkIds?.encodeToJSON()
        nillableDictionary["state_ids"] = self.stateIds?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
