//
// ZipCountiesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ZipCountiesResponse: JSONEncodable {
    /** Counties that exist in the provided zip prefix. */
    public var counties: [County]?
    /** States that exist in the provided zip prefix. */
    public var states: [State]?
    /** ZipCounties that exist in the provided zip prefix. */
    public var zipCounties: [ZipCounty]?
    /** ZipCodes that exist in the provided zip prefix. */
    public var zipCodes: [ZipCode]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["counties"] = self.counties?.encodeToJSON()
        nillableDictionary["states"] = self.states?.encodeToJSON()
        nillableDictionary["zip_counties"] = self.zipCounties?.encodeToJSON()
        nillableDictionary["zip_codes"] = self.zipCodes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
