//
// ZipCounty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ZipCounty: JSONEncodable {
    /** ID of the parent County in Vericred&#39;s API */
    public var countyId: Int32?
    /** Primary key */
    public var id: Int32?
    /** ID of the parent Zip Code in Vericred&#39;s API */
    public var zipCodeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["county_id"] = self.countyId?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["zip_code_id"] = self.zipCodeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
