//
// ZipCountyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ZipCountyResponse: JSONEncodable {
    /** Counties that exist in the provided zip prefix. */
    public var counties: [County]?
    /** States that exist in the provided zip prefix. */
    public var states: [State]?
    /** ZipCodes that exist in the provided zip prefix. */
    public var zipCodes: [ZipCode]?
    /** ZipCounty data */
    public var zipCounty: ZipCounty?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["counties"] = self.counties?.encodeToJSON()
        nillableDictionary["states"] = self.states?.encodeToJSON()
        nillableDictionary["zip_codes"] = self.zipCodes?.encodeToJSON()
        nillableDictionary["zip_county"] = self.zipCounty?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
